"""empty message

Revision ID: 4308cd638bdc
Revises: fdcf99602170
Create Date: 2022-07-25 08:03:42.322414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4308cd638bdc'
down_revision = 'fdcf99602170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_livre_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'livre_id')
    op.add_column('livres', sa.Column('categorie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'livres', 'categories', ['categorie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'livres', type_='foreignkey')
    op.drop_column('livres', 'categorie_id')
    op.add_column('categories', sa.Column('livre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_livre_id_fkey', 'categories', 'livres', ['livre_id'], ['id'])
    # ### end Alembic commands ###
